### ISSUE TITLE
.flatpak-builder/build/ grows too large

### ISSUE THREAD

**Issue by mcatanzaro** [endlessm/flapjack#10]
I've been using flapjack for less than a day, but my build cache under flapjack/.flatpak-builder/build has already grown to 11 GB. I see it has three subdirectories:

```
$ ls -hal ~/Projects/flapjack/.flatpak-builder/build/
total 20K
drwxrwxr-x.  5 mcatanzaro mcatanzaro 4.0K Jan 21 12:17 .
drwxrwxr-x.  7 mcatanzaro mcatanzaro 4.0K Jan 20 18:31 ..
lrwxrwxrwx.  1 mcatanzaro mcatanzaro   12 Jan 21 12:17 WebKitGTK+ -> WebKitGTK+-3
drwxrwxr-x. 18 mcatanzaro mcatanzaro 4.0K Jan 20 20:38 WebKitGTK+-1
drwxrwxr-x. 18 mcatanzaro mcatanzaro 4.0K Jan 21 12:10 WebKitGTK+-2
drwxrwxr-x. 18 mcatanzaro mcatanzaro 4.0K Jan 21 12:18 WebKitGTK+-3
```

WebKitGTK+-1 and WebKitGTK+-3 are both 3.5 GB, while WebKitGTK+-2 is 4.5 GB for some reason.

I don't know when exactly new directories are created or when the old directories are supposed to be deleted, but I suggest flapjack should be more aggressive about doing so. 11 GB is a lot. I hope it's not going to grow unbounded every time I run `flapjack build`.

**Comment by mcatanzaro** [comment]
Actually it's not just .flatpak-builder/build, but also .flatpak-builder/cache, which I hadn't noticed before. I'm now up to 14 GB under .flatpak-builder/build (a new WebKitGTK+-4 folder has appeared there), with .flatpak-builder/cache at 4 GB.

**Comment by ptomato** [comment]
This behaviour is because we pass `--keep-build-dirs` to flatpak-builder, and if I'm not mistaken it does throw away old ones eventually. WebKit is a bit of a painful case since it's so big. Normally the size of the build directory is not that noticeable.

However, I have never needed to use the old builds when building with Flapjack, only the most recent one, and only when it fails, so I would not be opposed to stopping the use of that option. The default behaviour is to keep failed builds but delete successful ones, which would be fine for my use case. I expect with WebKit that would still be painfully large, so I'm open to other suggestions that would work for you.

The cache, on the other hand, is required for flatpak-builder. You can delete it in between runs, but the build will get a lot slower. You would have to initialize the sandbox and build anything in your devtools manifest every time. On the other hand, the cache does not get bigger, since only the latest successful build is cached.
