### ISSUE TITLE
Error when trying to build (locale installed only partly)

### ISSUE THREAD

**Issue by jurf** [endlessm/flapjack#6]
So I followed the instructions up to the point of running `flapjack build`. So did so, waited a substantial while and then got this error:

```
❯ ~/.local/bin/flapjack build
Switched to a new branch 'flapjack'
Downloading sources
Initializing build dir
chyba: Požadované rozšírenie org.gnome.Sdk.Locale je nainštalované iba čiastočne (translation: error: needed extension is installed only partly)
Error: Dcérsky proces skončil s kódom 1 (translation: child process ended with code 1)
Switched to branch 'librsvg-2-40'
Your branch is up-to-date with 'origin/librsvg-2-40'.
```

And seemingly nothing built.

**Comment by ebassi** [comment]
Yes, this is a classic issue — so much so that Flatpak has grown a new command line option to deal with this situation:

```sh
$ flatpak update --subpath= org.gnome.Sdk.Locale
```

The command above will reinstall the Locale extension for `org.gnome.Sdk` with all the locales.

Ideally, we should double check all the extensions in use, and run the same command.
